### ISSUE TITLE
not sure what happened here.  build fails.

### ISSUE THREAD

**Issue by jnorthrup** [ScottPierce/kotlin-html#11]
https://gist.github.com/jnorthrup/7aab110f73be9c3e43b0a01ceb694fc3

**Comment by ScottPierce** [comment]
Pull latest. I fixed that earlier today.

**Comment by ScottPierce** [comment]
Actually - I was able to reproduce it. Still new to the multiplatform plugin. I guess js tests aren't built automatically in my CI process.

**Comment by ScottPierce** [comment]
What was the gradle command you ran out of curiosity?

**Comment by ScottPierce** [comment]
https://github.com/ScottPierce/kotlin-html/pull/12 Should fix this. Can you pull master and confirm this is fixed?

**Comment by jnorthrup** [comment]
sry, confirming, all good
