### ISSUE TITLE
Missing `b`, `strong` and `em` tags

### ISSUE THREAD

**Issue by Tmpod** [ScottPierce/kotlin-html#14]
The lib currently lacks some important tags, three of which are quite important for stylising text.

**Comment by ScottPierce** [comment]
So adding new tags is super trivial. You basically just add it to the generation list, and run the generator.

html isn't my day job. Is there any use-case at all where you'd assign an id, or a class to a `b`, `strong`, or `em`, or would you always use them without attributes?

**Comment by ScottPierce** [comment]
Closing since this should be fixed with https://github.com/ScottPierce/kotlin-html/pull/15. I've merged it and a new build is out - `0.2.10`.

Please re-open this if you try `0.2.10` and something isn't working / seems off!

**Comment by Tmpod** [comment]
:ok_hand:
