### ISSUE TITLE
Add universal `inherit` and `initial` values for all CSS properties

### ISSUE THREAD

**Issue by Tmpod** [ScottPierce/kotlin-html#18]
Since all props can have the `inherit` and `initial` values, the lib should have "universal" constants for them that could be applied to any property.
What do you think? If you think it's a good idea, I might try to do it myself.

*PS: This is unrelated to this issue but is there any other platform I could contact you through?*

EDIT: Also included the `initial` property.

**Comment by ScottPierce** [comment]
Dm me in the kotlin slack channel works. I've actually messaged you there a
few days ago :P

This is the first I've heard of inherit. Let me do some reading on it.

**Comment by ScottPierce** [comment]
Oh - I know what you mean by inherit now. That's a good point. I'm not sure how to apply that. I'll do some thinking.

**Comment by ScottPierce** [comment]
https://github.com/ScottPierce/kotlin-html/pull/23 Takes care of this. It also drastically improves the completeness of the existing styles.

**Comment by ScottPierce** [comment]
Open this back up or comment if you find it lacking. I'll release it as a new version soon.
