### ISSUE TITLE
`!important` CSS property modifier is missing

### ISSUE THREAD

**Issue by Tmpod** [ScottPierce/kotlin-html#30]
At the moment, it's impossible to give the `!important` modifier to a CSS property without writing it manually with the `writeStyleProperty` method. It is a core flag that is missing in the lib.

**Comment by ScottPierce** [comment]
https://github.com/ScottPierce/kotlin-html/pull/32 was created to solve this.

**Comment by ScottPierce** [comment]
Check out `0.7.12`, and re-open this if this isn't working for you.
