### ISSUE TITLE
Compilation speed benchmark

### ISSUE THREAD

**Issue by cies** [ScottPierce/kotlin-html#39]
Just found out about this project. Give my main issue with Kotlinx.html is not its render speed, but it's compilation speed: it slows down our build considerably (several x slower since porting our templates from "HTML-strings with Groovy sprinkled in"). I really wonder if this library would also help in that regard.

**Comment by ScottPierce** [comment]
Not sure. Feel free to give it a shot.

**Comment by ScottPierce** [comment]
This is compiling to a fairly large inline function in most cases.
